services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DEBUG: "true"
    volumes:
      - .:/app
      - ./data:/data
      - ./keys:/app/keys
